export const INITIALIZED = "example.app.INITIALIZED";
export const ROOT_CHANGED = "example.app.ROOT_CHANGED";
export const USER_REGISTERATION = "USER_REGISTERATION";
export const SET_NAVIGATOR = "SET_NAVIGATOR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOADING = "LOADING";

export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const INSTITUTIONS = "INSTITUTIONS";
export const INSTITUTIONS_FAIL = "INSTITUTIONS_FAIL";

export const USER_DATA_SIGNUP = "USER_DATA_SIGNUP";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const IS_INTROSCREEN_WATHCED = "IS_INTROSCREEN_WATHCED";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_FAIL = "REGISTER_REQUEST_FAIL";

export const VERIFY_REQUEST_SUCCESS = "VERIFY_REQUEST_SUCCESS";
export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_REQUEST_FAIL = "VERIFY_REQUEST_FAIL";

export const POSIMATION_REQUEST = "POSIMATION_REQUEST";
export const POSIMATION_SUCESS = "POSIMATION_SUCESS";
export const POSIMATION_FAIL = "POSIMATION_FAIL";

export const POSIMATION_DELETE_REQUEST = "POSIMATION_DELETE_REQUEST";
export const POSIMATION_DELETE_SUCESS = "POSIMATION_DELETE_SUCESS";
export const POSIMATION_DELETE_FAIL = "POSIMATION_DELETE_FAIL";

export const BOT_IMAGE_SET = "BOT_IMAGE_SET";
export const BOT_CHAT_IMAGE_SET = "BOT_CHAT_IMAGE_SET";
export const BOT_NAME_CHANGE = "BOT_NAME_CHANGE";
export const BOT_SWITCH = "BOT_SWITCH";
export const SLOT_SAVE = "SLOT_SAVE";
export const TEXT_INPUT_CHAT = "TEXT_INPUT_CHAT";
export const TEXT_INPUT_TEN_NUMBER = "TEXT_INPUT_TEN_NUMBER";
export const TEXT_INPUT_ADD_MESSAGE = "TEXT_INPUT_ADD_MESSAGE";
export const RECURSION_VALUE_SET = "RECURSION_VALUE_SET";
export const TEXT_INPUT_NUMBER = "TEXT_INPUT_NUMBER";
export const POPOVERVIEW = "POPOVERVIEW";
export const VIDEO_BUTTON = "VIDEO_BUTTON";
export const VIDEO_SAVE = "VIDEO_SAVE";
export const VIDEO_PERCENTAGE_SET = "VIDEO_PERCENTAGE_SET";
export const AVATAR_IMAGES = "AVATAR_IMAGES";
export const AVATAR_IMAGES_FAIL = "AVATAR_IMAGES_FAIL";
export const SET_FCM_DEVICE_TOKEN = "SET_FCM_DEVICE_TOKEN";
export const RESEND_CODE = "RESEND_CODE";
export const SEND_BACK_TO_SERVER = "SEND_BACK_TO_SERVER";
export const SET_GUIDE_DESCRIPTION = "SET_GUIDE_DESCRIPTION";

export const OOZ_CHALLENGE_SHOW = "OOZ_CHALLENGE_SHOW";
export const SELECTED_TAB = "SELECTED_TAB";
export const LOGIN_USER = "LOGIN_USER";
export const SKIP_PROMPT_BUTTON = "SKIP_PROMPT_BUTTON";
export const CHALLENGE_TAB_PUSHED = "CHALLENGE_TAB_PUSHED";
export const END_OF_VALIDATION_TIMESTAMP = "END_OF_VALIDATION_TIMESTAMP";
export const TEXT_INPUT_CHAT_CLOSE_ALL = "TEXT_INPUT_CHAT_CLOSE_ALL";
export const AJIVAR_GUIDE_SHOW_OR_NOT = "AJIVAR_GUIDE_SHOW_OR_NOT";
export const CLEAR_STEPS = "CLEAR_STEPS";
export const CLEAR_POSIMATION_DATA = "CLEAR_POSIMATION_DATA";
